/* ============================================================
   Slotly Desk — the in-app assistant.
   Every answer is computed from the live store: change a booking and
   the next answer changes with it. Nothing is fetched, nothing is
   generated by a model — intents are matched locally and the numbers
   come straight out of the demo data.

   Two kinds of intent live here. The ones in this file read and report.
   The ones in actions.js propose a change and apply it when the reader
   presses the button on the answer.
   ============================================================ */

import { Assistant } from '../lib/assistant.js';
import {
  todayKey, addDays, weekStart, parseDay, dayLabel, relativeDay, hm12,
  freeSlots, nextAvailable, utilisation, hourLoad, customerStats, isOpenDay,
  svcOf, staffOf, custOf, tokenLabel, staffWorks, shiftMinutes, gridSlots,
  STATUS, DOW_LONG,
} from './data.js';
import { matchDay, matchService, matchStaff, matchCustomer } from './parse.js';
import { actionIntents, ACTION_CHIPS } from './actions.js';

const money = (state, n) => `${state.settings.currency}${Number(n || 0).toLocaleString('en-IN')}`;
const live = (state, from, to) => state.bookings.filter((b) => b.date >= from && b.date <= to && b.status !== 'cancelled');

/* ---------- intents ---------- */
function intents() {
  return [
    {
      id: 'free-slots',
      match: [/free|available|availability|open slot|vacan|any space|any room|book(?:able)? slot/i, 'slots on', 'what is free'],
      trace: 'walked the rota against every booked block',
      answer: (q, state) => {
        let key = matchDay(q) || todayKey();
        const serviceId = matchService(state, q) || (state.services.find((s) => s.active) || {}).id;
        const staffId = matchStaff(state, q);
        const svc = svcOf(state, serviceId);
        let note = '';
        if (!isOpenDay(state, key)) {
          const shut = DOW_LONG[parseDay(key).getDay()];
          let roll = key;
          for (let i = 1; i <= 7 && !isOpenDay(state, roll); i += 1) roll = addDays(key, i);
          note = `The desk is closed on ${shut}, so I rolled forward to ${relativeDay(roll)}.\n\n`;
          key = roll;
        }
        const slots = freeSlots(state, key, serviceId, staffId);
        if (!slots.length) {
          const nx = nextAvailable(state, serviceId, staffId, key);
          return {
            text: note + `**${svc.name}** has nothing free on ${relativeDay(key)}${staffId ? ` with ${staffOf(state, staffId).name}` : ''}.`
              + (nx ? `\n\nThe first opening is ${relativeDay(nx.date)} at **${hm12(nx.time)}** with ${staffOf(state, nx.staffIds[0]).name}.` : '\n\nNothing opens up in the next three weeks either.'),
            meta: `checked ${gridSlots(state).length} grid slots`,
          };
        }
        const rows = slots.slice(0, 10).map((s) => [
          `**${hm12(s.time)}**`,
          s.staffIds.map((id) => staffOf(state, id).name.split(' ')[0]).join(', '),
        ]);
        return {
          text: note + `**${slots.length} open slot${slots.length === 1 ? '' : 's'}** for ${svc.name} on ${relativeDay(key)}`
            + `${staffId ? ` with ${staffOf(state, staffId).name}` : ''}. Each one holds the full ${svc.durationMin + svc.bufferMin} minute block.`,
          table: { head: ['Time', 'Who is free'], rows },
          meta: `${slots.length} of ${gridSlots(state).length} grid slots open`,
          suggestions: ["Today's load", 'Busiest hour', 'Who might not turn up'],
        };
      },
    },
    {
      id: 'next-available',
      match: [/next available|earliest|soonest|first free|when can (?:i|we|you)|next opening/i,
        'next available', 'earliest', 'soonest', 'first free', 'next opening', 'next slot'],
      trace: 'scanned forward 21 days across the rota',
      answer: (q, state) => {
        const staffId = matchStaff(state, q);
        const serviceId = matchService(state, q) || (state.services.find((s) => s.active) || {}).id;
        const svc = svcOf(state, serviceId);
        const nx = nextAvailable(state, serviceId, staffId, todayKey());
        if (!nx) {
          return { text: `Nothing opens for **${svc.name}**${staffId ? ` with ${staffOf(state, staffId).name}` : ''} in the next three weeks. Either the rota has no shift with that skill or every block is taken.` };
        }
        const alt = state.staff
          .filter((st) => st.active && st.skills.includes(serviceId) && st.id !== nx.staffIds[0])
          .map((st) => {
            const n = nextAvailable(state, serviceId, st.id, todayKey());
            return n ? [st.name, `${relativeDay(n.date)} ${hm12(n.time)}`] : [st.name, 'nothing in 21 days'];
          });
        return {
          text: `Earliest **${svc.name}**${staffId ? ` with ${staffOf(state, staffId).name}` : ''} is **${relativeDay(nx.date)} at ${hm12(nx.time)}**`
            + `${staffId ? '' : ` — ${staffOf(state, nx.staffIds[0]).name} takes it`}. That is ${dayLabel(nx.date)}.`,
          table: alt.length ? { head: ['Other staff', 'Their first opening'], rows: alt } : null,
          suggestions: ['Free slots on Friday', "Today's load", 'Busiest hour'],
        };
      },
    },
    {
      id: 'queue-now',
      match: [/queue|now serving|who is waiting|who'?s waiting|token|called|next up/i, 'waiting'],
      trace: 'read the live queue for today',
      answer: (q, state) => {
        const key = todayKey();
        const day = state.bookings.filter((b) => b.date === key && b.status !== 'cancelled')
          .sort((a, b) => a.time.localeCompare(b.time));
        const serving = day.find((b) => b.status === 'serving');
        const waiting = day.filter((b) => b.status === 'booked' || b.status === 'called');
        if (!day.length) return { text: `Nothing is booked for ${relativeDay(key)}, so the queue is empty.` };
        const rows = waiting.slice(0, 8).map((b) => [
          `**${tokenLabel(state, b)}**`, hm12(b.time), custOf(state, b.customerId).name,
          svcOf(state, b.serviceId).code, (STATUS[b.status] || {}).label || b.status,
        ]);
        return {
          text: serving
            ? `**${tokenLabel(state, serving)}** is at the chair now — ${custOf(state, serving.customerId).name}, ${svcOf(state, serving.serviceId).name} with ${staffOf(state, serving.staffId).name}. **${waiting.length}** still waiting.`
            : `Nobody is being served right now. **${waiting.length}** token${waiting.length === 1 ? '' : 's'} still waiting today.`,
          table: rows.length ? { head: ['Token', 'Time', 'Customer', 'Service', 'State'], rows } : null,
          meta: `${day.length} bookings on today's sheet`,
          suggestions: ["Today's load", 'Who might not turn up', 'Free slots tomorrow'],
        };
      },
    },
    {
      id: 'today-load',
      match: [/today'?s load|how busy|load today|busy today|how many.*(today|booked)|capacity today/i, 'load'],
      trace: 'totalled booked minutes against shift minutes',
      answer: (q, state) => {
        const key = matchDay(q) || todayKey();
        const day = state.bookings.filter((b) => b.date === key && b.status !== 'cancelled');
        const util = utilisation(state, key);
        const done = day.filter((b) => b.status === 'done');
        const takings = done.reduce((n, b) => n + svcOf(state, b.serviceId).priceInr, 0);
        if (!isOpenDay(state, key)) return { text: `${dayLabel(key)} is a closed day, so the sheet is empty.` };
        return {
          text: `${relativeDay(key)} holds **${day.length} bookings** across ${state.staff.filter((s) => staffWorks(state, s.id, key)).length} staff on shift.`
            + `\n\n- Chair time booked: **${util.pct}%** (${util.used} of ${util.capacity} minutes)`
            + `\n- Completed: ${done.length}, billed ${money(state, takings)}`
            + `\n- No-shows so far: ${day.filter((b) => b.status === 'no-show').length}`,
          table: {
            head: ['Staff', 'Bookings', 'Booked min', 'Load'],
            rows: util.perStaff.map((p) => [
              p.name,
              String(day.filter((b) => b.staffId === p.staffId).length),
              p.capacity ? `${p.booked} / ${p.capacity}` : 'day off',
              p.capacity ? `**${p.pct}%**` : '—',
            ]),
          },
          suggestions: ['Busiest hour', 'Free slots tomorrow', 'Who might not turn up'],
        };
      },
    },
    {
      id: 'busiest-hour',
      match: [/busiest|peak|quietest|slowest|which hour|what time.*busy|rush/i, 'busiest hour'],
      trace: 'grouped 30 days of bookings by opening hour',
      answer: (q, state) => {
        const from = addDays(todayKey(), -30);
        const to = addDays(todayKey(), 7);
        const load = hourLoad(state, from, to);
        if (!load.length) return { text: 'There is nothing in the last 30 days to group by hour yet.' };
        const sorted = load.slice().sort((a, b) => b.count - a.count);
        const top = sorted[0];
        const quiet = sorted[sorted.length - 1];
        return {
          text: `Across the last 30 days and the week ahead, **${hm12(top.hour)}–${hm12(`${String(Number(top.hour.slice(0, 2)) + 1).padStart(2, '0')}:00`)}** is the rush with **${top.count} bookings**.`
            + `\n\nThe quietest open hour is ${hm12(quiet.hour)} with ${quiet.count}. Two extra ${svcOf(state, 'svc-lab').code || 'short'} blocks there would not cost you a busy slot.`,
          table: {
            head: ['Hour', 'Bookings'],
            rows: load.map((r) => [hm12(r.hour), r.hour === top.hour ? `**${r.count}**` : String(r.count)]),
          },
          suggestions: ["Today's load", 'Free slots on Friday', 'Which service earns most'],
        };
      },
    },
    {
      id: 'no-show-risk',
      match: [/no.?show|turn(?:s|ed|ing)? up|show(?:s|ed)? up|miss(?:es|ed|ing)?\b|skip|risk|reminder call|unreliable/i, 'no show'],
      trace: 'scored every customer on missed against settled bookings',
      answer: (q, state) => {
        const named = matchCustomer(state, q);
        if (named) {
          const st = customerStats(state, named.id);
          return {
            text: `**${named.name}** has missed **${st.noShows}** of ${st.attended + st.noShows} settled bookings — a no-show rate of **${st.rate}%**.`
              + `\n\n${st.upcoming ? `${st.upcoming} booking ahead. Worth a reminder call the evening before.` : 'Nothing booked ahead right now.'}`,
            meta: `${st.total} records on file`,
          };
        }
        const key = todayKey();
        const risky = state.customers
          .map((c) => ({ c, st: customerStats(state, c.id) }))
          .filter((r) => r.st.noShows >= 2 && r.st.rate >= 20)
          .sort((a, b) => b.st.rate - a.st.rate)
          .slice(0, 6);
        const todayRisky = state.bookings.filter((b) => b.date === key
          && (b.status === 'booked' || b.status === 'called')
          && risky.some((r) => r.c.id === b.customerId));
        return {
          text: `**${risky.length} customers** are carrying a no-show rate of 20% or more.`
            + `\n\n${todayRisky.length ? `**${todayRisky.length}** of them are on today's sheet: ${todayRisky.map((b) => `${custOf(state, b.customerId).name} at ${hm12(b.time)}`).join(', ')}.` : 'None of them are booked today.'}`,
          table: {
            head: ['Customer', 'Missed', 'Rate', 'Booked ahead'],
            rows: risky.map((r) => [r.c.name, String(r.st.noShows), `**${r.st.rate}%**`, String(r.st.upcoming)]),
          },
          suggestions: ['Queue right now', "Today's load", 'Cancellations this week'],
        };
      },
    },
    {
      id: 'staff-load',
      match: [/utilisation|utilization|workload|how busy is|rota|working hours|who is on|who'?s on|shift|day off/i, 'staff'],
      trace: 'summed shift minutes across the current week',
      answer: (q, state) => {
        const staffId = matchStaff(state, q);
        const week = weekStart(todayKey());
        const days = Array.from({ length: 7 }, (_, i) => addDays(week, i));
        const pool = staffId ? state.staff.filter((s) => s.id === staffId) : state.staff;
        const rows = pool.map((st) => {
          const cap = days.reduce((n, d) => n + shiftMinutes(state, st.id, d), 0);
          const booked = live(state, days[0], days[6]).filter((b) => b.staffId === st.id);
          const mins = booked.reduce((n, b) => n + b.blockMin, 0);
          return [st.name, String(booked.length), `${mins} / ${cap}`, `**${cap ? Math.round((mins / cap) * 100) : 0}%**`];
        });
        const st = staffId ? staffOf(state, staffId) : null;
        return {
          text: st
            ? `**${st.name}** (${st.role}) works ${st.days.map((d) => DOW_LONG[d].slice(0, 3)).join(', ')}, ${hm12(st.start)} to ${hm12(st.end)}, break ${hm12(st.breakStart)}–${hm12(st.breakEnd)}, in ${st.room}. Skills: ${st.skills.map((id) => svcOf(state, id).name).join(', ')}.`
            : `Week of ${dayLabel(week)} — booked minutes against shift minutes for each person.`,
          table: { head: ['Staff', 'Bookings', 'Minutes', 'Load'], rows },
          suggestions: ['Next available with Anwar', "Today's load", 'Free slots tomorrow'],
        };
      },
    },
    {
      id: 'service-mix',
      match: [/most booked|popular|top service|service mix|which service|best selling|earns most/i, 'services'],
      trace: 'grouped 30 days of completed appointments by service',
      answer: (q, state) => {
        const from = addDays(todayKey(), -30);
        const rows = state.services.map((s) => {
          const list = state.bookings.filter((b) => b.serviceId === s.id && b.date >= from && b.date <= todayKey() && b.status === 'done');
          return { s, count: list.length, rev: list.length * s.priceInr };
        }).sort((a, b) => b.rev - a.rev);
        const top = rows[0];
        const total = rows.reduce((n, r) => n + r.rev, 0);
        return {
          text: `Over the last 30 days the desk billed **${money(state, total)}** across ${rows.reduce((n, r) => n + r.count, 0)} completed appointments.`
            + `\n\n**${top.s.name}** leads on money at ${money(state, top.rev)} from ${top.count} appointments.`,
          table: {
            head: ['Service', 'Done', 'Billed', 'Block'],
            rows: rows.map((r) => [r.s.name, String(r.count), money(state, r.rev), `${r.s.durationMin + r.s.bufferMin}m`]),
          },
          suggestions: ['Busiest hour', 'Takings this week', 'Free slots tomorrow'],
        };
      },
    },
    {
      id: 'revenue',
      match: [/revenue|takings|billed|income|money|earned|how much/i, 'takings'],
      trace: 'priced completed bookings against the service list',
      answer: (q, state) => {
        const t = todayKey();
        const week = weekStart(t);
        const sum = (from, to) => state.bookings
          .filter((b) => b.date >= from && b.date <= to && b.status === 'done')
          .reduce((n, b) => n + svcOf(state, b.serviceId).priceInr, 0);
        const booked = state.bookings
          .filter((b) => b.date >= t && (b.status === 'booked' || b.status === 'called' || b.status === 'serving'))
          .reduce((n, b) => n + svcOf(state, b.serviceId).priceInr, 0);
        return {
          text: `Takings from completed appointments:`
            + `\n\n- Today: **${money(state, sum(t, t))}**`
            + `\n- This week so far: **${money(state, sum(week, t))}**`
            + `\n- Last 30 days: **${money(state, sum(addDays(t, -30), t))}**`
            + `\n\nStill on the book from today onward: ${money(state, booked)} across ${state.bookings.filter((b) => b.date >= t && b.status === 'booked').length} open bookings.`,
          meta: 'no-shows and cancellations are not billed',
          suggestions: ['Which service earns most', "Today's load", 'Cancellations this week'],
        };
      },
    },
    {
      id: 'cancellations',
      match: [/cancel|cancellation|dropped|released|freed up/i, 'cancellations'],
      trace: 'compared cancelled records against the same period last fortnight',
      answer: (q, state) => {
        const t = todayKey();
        const week = weekStart(t);
        const end = addDays(week, 6);
        const thisWeek = state.bookings.filter((b) => b.date >= week && b.date <= end && b.status === 'cancelled');
        const prev = state.bookings.filter((b) => b.date >= addDays(week, -7) && b.date < week && b.status === 'cancelled');
        const byStaff = state.staff.map((st) => [st.name, String(thisWeek.filter((b) => b.staffId === st.id).length)]);
        return {
          text: `**${thisWeek.length} cancellation${thisWeek.length === 1 ? '' : 's'}** in the week of ${dayLabel(week)}, against ${prev.length} the week before.`
            + `\n\nThose released **${thisWeek.reduce((n, b) => n + b.blockMin, 0)} minutes** back onto the grid — they show as free slots again in the calendar.`,
          table: { head: ['Staff', 'Cancelled this week'], rows: byStaff },
          suggestions: ['Who might not turn up', 'Free slots tomorrow', "Today's load"],
        };
      },
    },
    {
      id: 'customer-lookup',
      match: [/history for|tell me about|customer|record for|has .* been|when did .* last/i, 'history'],
      trace: 'pulled the customer record and every linked booking',
      answer: (q, state) => {
        const c = matchCustomer(state, q);
        if (!c) {
          return {
            text: 'I could not pick a name out of that. Ask me with the customer name in it, for example `history for Meera` — the desk holds '
              + `${state.customers.length} customers.`,
            suggestions: ['Who might not turn up', 'Queue right now', "Today's load"],
          };
        }
        const st = customerStats(state, c.id);
        const recent = state.bookings.filter((b) => b.customerId === c.id)
          .sort((a, b) => b.date.localeCompare(a.date)).slice(0, 5);
        return {
          text: `**${c.name}** · ${c.phone} · on file since ${dayLabel(c.since)}.`
            + `\n\n- ${st.attended} visits kept, ${st.noShows} missed, ${st.cancelled} cancelled`
            + `\n- No-show rate **${st.rate}%**`
            + `\n- Billed ${money(state, st.spend)} in total`
            + `\n- ${st.upcoming ? `${st.upcoming} booking ahead` : 'nothing booked ahead'}`,
          table: {
            head: ['Date', 'Service', 'Staff', 'Outcome'],
            rows: recent.map((b) => [dayLabel(b.date), svcOf(state, b.serviceId).code, staffOf(state, b.staffId).name.split(' ')[0], (STATUS[b.status] || {}).label || b.status]),
          },
          suggestions: ['Who might not turn up', 'Next available with Rehana'],
        };
      },
    },
    {
      id: 'desk-setup',
      match: [/opening hours|slot length|template|confirmation message|closed day|settings|how long is a slot/i, 'opening hours'],
      trace: 'read the desk configuration',
      answer: (q, state) => {
        const s = state.settings;
        return {
          text: `**${s.deskName}** — ${s.branch}.`
            + `\n\n- Open ${hm12(s.openTime)} to ${hm12(s.closeTime)}, ${gridSlots(state).length} slots a day at ${s.slotMinutes} minutes each`
            + `\n- Closed on ${s.closedDays.length ? s.closedDays.map((d) => DOW_LONG[d]).join(', ') : 'no fixed day'}`
            + `\n- Tokens run ${s.tokenPrefix}001 upward, reset each day`
            + `\n- ${state.services.filter((x) => x.active).length} bookable services, ${state.staff.filter((x) => x.active).length} staff taking bookings`
            + `\n\nThe confirmation template currently reads: \`${s.confirmTemplate.slice(0, 90)}…\``,
          suggestions: ["Today's load", 'Free slots tomorrow', 'Which service earns most'],
        };
      },
    },
  ];
}

export function buildAgent(ctx) {
  return new Assistant({
    name: 'Slotly Desk',
    initials: 'SD',
    tag: 'Front desk agent · demo',
    greeting: 'I read the live rota in this browser, and I can change it. Ask me what is free or how loaded a day is — or tell me to book someone in, move a booking, cancel one, call the next token, hold a staff member\'s afternoon or change a service. Ask **what can you do?** for the full list.',
    suggestions: ACTION_CHIPS,
    note: 'Simulated agent — answers are matched against this app\'s own demo data. No connected model, no request leaves your browser.',
    intents: [...intents(), ...actionIntents(ctx)],
    fallbacks: [
      'I can only work from this desk\'s own data. Try: "what is free on Friday for physiotherapy".',
      'Not something I hold. Ask me about the queue, the rota, no-show rates or takings — or ask what I can change.',
      'I did not catch a date, a service or a name in that. Ask me which slots are free on Friday and I will pull the rota.',
      'That one is outside the demo data set. Try "next available with Anwar", "busiest hour", or "what can you do?".',
    ],
    context: () => ctx.state,
  });
}

export { matchDay, matchService, matchStaff, matchCustomer };