/* ============================================================
   Slotly Desk — the in-app assistant.
   Every answer is computed from the live store: change a booking and
   the next answer changes with it. Nothing is fetched, nothing is
   generated by a model — intents are matched locally and the numbers
   come straight out of the demo data.

   Two kinds of intent live here. The ones in this file read and report.
   The ones in actions.js propose a change and apply it when the reader
   presses the button on the answer.

   Every reader-facing string comes from the dictionary through `t`.
   `t` is re-exported by main.js, which imports this module, so it is
   still in its temporal dead zone while this file evaluates — every
   call below therefore sits inside a function body, never at the top
   level.
   ============================================================ */

import { Assistant } from '../lib/assistant.js';
import {
  todayKey, addDays, weekStart, parseDay, dayLabel, relativeDay, hm12,
  freeSlots, nextAvailable, utilisation, hourLoad, customerStats, isOpenDay,
  svcOf, staffOf, custOf, tokenLabel, staffWorks, shiftMinutes, gridSlots,
  STATUS, dowLong,
  svcName, staffRole, staffRoom, deskName, branchName,
} from './data.js';
import { t } from './main.js';
import { matchDay, matchService, matchStaff, matchCustomer } from './parse.js';
import { actionIntents, actionChips } from './actions.js';

const money = (state, n) => `${state.settings.currency}${Number(n || 0).toLocaleString('en-IN')}`;
const live = (state, from, to) => state.bookings.filter((b) => b.date >= from && b.date <= to && b.status !== 'cancelled');

/* ---------- intents ---------- */
function intents() {
  return [
    {
      id: 'free-slots',
      match: [/free|available|availability|open slot|vacan|any space|any room|book(?:able)? slot/i, 'slots on', 'what is free'],
      trace: t('ans.trace.freeSlots'),
      answer: (q, state) => {
        let key = matchDay(q) || todayKey();
        const serviceId = matchService(state, q) || (state.services.find((s) => s.active) || {}).id;
        const staffId = matchStaff(state, q);
        const svc = svcOf(state, serviceId);
        let note = '';
        if (!isOpenDay(state, key)) {
          const shut = dowLong(parseDay(key).getDay());
          let roll = key;
          for (let i = 1; i <= 7 && !isOpenDay(state, roll); i += 1) roll = addDays(key, i);
          note = t('ans.freeSlots.rolled', { day: shut, to: relativeDay(roll) });
          key = roll;
        }
        const slots = freeSlots(state, key, serviceId, staffId);
        if (!slots.length) {
          const nx = nextAvailable(state, serviceId, staffId, key);
          return {
            text: note + t('ans.freeSlots.none', {
              service: svcName(svc),
              day: relativeDay(key),
              staff: staffId ? staffOf(state, staffId).name : '',
            })
              + (nx
                ? t('ans.freeSlots.firstOpening', {
                  day: relativeDay(nx.date), time: hm12(nx.time), staff: staffOf(state, nx.staffIds[0]).name,
                })
                : t('ans.freeSlots.nothingAhead')),
            meta: t('ans.freeSlots.checked', { n: gridSlots(state).length }),
          };
        }
        const rows = slots.slice(0, 10).map((s) => [
          `**${hm12(s.time)}**`,
          s.staffIds.map((id) => staffOf(state, id).name.split(' ')[0]).join(', '),
        ]);
        return {
          text: note + t('ans.freeSlots.head', {
            n: slots.length,
            service: svcName(svc),
            day: relativeDay(key),
            staff: staffId ? staffOf(state, staffId).name : '',
            block: svc.durationMin + svc.bufferMin,
          }),
          table: { head: t('ans.freeSlots.cols'), rows },
          meta: t('ans.freeSlots.meta', { open: slots.length, total: gridSlots(state).length }),
          suggestions: [t('ans.chips.todayLoad'), t('ans.chips.busiest'), t('ans.chips.noShow')],
        };
      },
    },
    {
      id: 'next-available',
      match: [/next available|earliest|soonest|first free|when can (?:i|we|you)|next opening/i,
        'next available', 'earliest', 'soonest', 'first free', 'next opening', 'next slot'],
      trace: t('ans.trace.nextAvailable'),
      answer: (q, state) => {
        const staffId = matchStaff(state, q);
        const serviceId = matchService(state, q) || (state.services.find((s) => s.active) || {}).id;
        const svc = svcOf(state, serviceId);
        const nx = nextAvailable(state, serviceId, staffId, todayKey());
        if (!nx) {
          return {
            text: t('ans.nextAvailable.none', {
              service: svcName(svc),
              staff: staffId ? staffOf(state, staffId).name : '',
            }),
          };
        }
        const alt = state.staff
          .filter((st) => st.active && st.skills.includes(serviceId) && st.id !== nx.staffIds[0])
          .map((st) => {
            const n = nextAvailable(state, serviceId, st.id, todayKey());
            return n ? [st.name, `${relativeDay(n.date)} ${hm12(n.time)}`] : [st.name, t('ans.nextAvailable.nothing21')];
          });
        return {
          text: t('ans.nextAvailable.text', {
            service: svcName(svc),
            staff: staffId ? staffOf(state, staffId).name : '',
            day: relativeDay(nx.date),
            time: hm12(nx.time),
            taker: staffId ? '' : staffOf(state, nx.staffIds[0]).name,
            full: dayLabel(nx.date),
          }),
          table: alt.length ? { head: t('ans.nextAvailable.cols'), rows: alt } : null,
          suggestions: [t('ans.chips.freeFriday'), t('ans.chips.todayLoad'), t('ans.chips.busiest')],
        };
      },
    },
    {
      id: 'queue-now',
      match: [/queue|now serving|who is waiting|who'?s waiting|token|called|next up/i, 'waiting'],
      trace: t('ans.trace.queue'),
      answer: (q, state) => {
        const key = todayKey();
        const day = state.bookings.filter((b) => b.date === key && b.status !== 'cancelled')
          .sort((a, b) => a.time.localeCompare(b.time));
        const serving = day.find((b) => b.status === 'serving');
        const waiting = day.filter((b) => b.status === 'booked' || b.status === 'called');
        if (!day.length) return { text: t('ans.queue.empty', { day: relativeDay(key) }) };
        const rows = waiting.slice(0, 8).map((b) => [
          `**${tokenLabel(state, b)}**`, hm12(b.time), custOf(state, b.customerId).name,
          svcOf(state, b.serviceId).code, (STATUS[b.status] || {}).label || b.status,
        ]);
        return {
          text: serving
            ? t('ans.queue.serving', {
              token: tokenLabel(state, serving),
              name: custOf(state, serving.customerId).name,
              service: svcName(svcOf(state, serving.serviceId)),
              staff: staffOf(state, serving.staffId).name,
              waiting: waiting.length,
            })
            : t('ans.queue.idle', { waiting: waiting.length }),
          table: rows.length ? { head: t('ans.queue.cols'), rows } : null,
          meta: t('ans.queue.meta', { n: day.length }),
          suggestions: [t('ans.chips.todayLoad'), t('ans.chips.noShow'), t('ans.chips.freeTomorrow')],
        };
      },
    },
    {
      id: 'today-load',
      match: [/today'?s load|how busy|load today|busy today|how many.*(today|booked)|capacity today/i, 'load'],
      trace: t('ans.trace.load'),
      answer: (q, state) => {
        const key = matchDay(q) || todayKey();
        const day = state.bookings.filter((b) => b.date === key && b.status !== 'cancelled');
        const util = utilisation(state, key);
        const done = day.filter((b) => b.status === 'done');
        const takings = done.reduce((n, b) => n + svcOf(state, b.serviceId).priceInr, 0);
        if (!isOpenDay(state, key)) return { text: t('ans.load.closed', { day: dayLabel(key) }) };
        return {
          text: t('ans.load.text', {
            day: relativeDay(key),
            n: day.length,
            staff: state.staff.filter((s) => staffWorks(state, s.id, key)).length,
            pct: util.pct,
            used: util.used,
            capacity: util.capacity,
            done: done.length,
            money: money(state, takings),
            noShows: day.filter((b) => b.status === 'no-show').length,
          }),
          table: {
            head: t('ans.load.cols'),
            rows: util.perStaff.map((p) => [
              p.name,
              String(day.filter((b) => b.staffId === p.staffId).length),
              p.capacity ? `${p.booked} / ${p.capacity}` : t('ans.load.dayOff'),
              p.capacity ? `**${p.pct}%**` : t('common.none'),
            ]),
          },
          suggestions: [t('ans.chips.busiest'), t('ans.chips.freeTomorrow'), t('ans.chips.noShow')],
        };
      },
    },
    {
      id: 'busiest-hour',
      match: [/busiest|peak|quietest|slowest|which hour|what time.*busy|rush/i, 'busiest hour'],
      trace: t('ans.trace.busiest'),
      answer: (q, state) => {
        const from = addDays(todayKey(), -30);
        const to = addDays(todayKey(), 7);
        const load = hourLoad(state, from, to);
        if (!load.length) return { text: t('ans.busiest.none') };
        const sorted = load.slice().sort((a, b) => b.count - a.count);
        const top = sorted[0];
        const quiet = sorted[sorted.length - 1];
        return {
          text: t('ans.busiest.text', {
            from: hm12(top.hour),
            to: hm12(`${String(Number(top.hour.slice(0, 2)) + 1).padStart(2, '0')}:00`),
            count: top.count,
            quietHour: hm12(quiet.hour),
            quietCount: quiet.count,
            code: svcOf(state, 'svc-lab').code || t('ans.busiest.shortCode'),
          }),
          table: {
            head: t('ans.busiest.cols'),
            rows: load.map((r) => [hm12(r.hour), r.hour === top.hour ? `**${r.count}**` : String(r.count)]),
          },
          suggestions: [t('ans.chips.todayLoad'), t('ans.chips.freeFriday'), t('ans.chips.earnsMost')],
        };
      },
    },
    {
      id: 'no-show-risk',
      match: [/no.?show|turn(?:s|ed|ing)? up|show(?:s|ed)? up|miss(?:es|ed|ing)?\b|skip|risk|reminder call|unreliable/i, 'no show'],
      trace: t('ans.trace.noShow'),
      answer: (q, state) => {
        const named = matchCustomer(state, q);
        if (named) {
          const st = customerStats(state, named.id);
          return {
            text: t('ans.noShow.named', {
              name: named.name,
              missed: st.noShows,
              settled: st.attended + st.noShows,
              rate: st.rate,
            })
              + (st.upcoming ? t('ans.noShow.ahead', { n: st.upcoming }) : t('ans.noShow.noneAhead')),
            meta: t('ans.noShow.meta', { n: st.total }),
          };
        }
        const key = todayKey();
        const risky = state.customers
          .map((c) => ({ c, st: customerStats(state, c.id) }))
          .filter((r) => r.st.noShows >= 2 && r.st.rate >= 20)
          .sort((a, b) => b.st.rate - a.st.rate)
          .slice(0, 6);
        const todayRisky = state.bookings.filter((b) => b.date === key
          && (b.status === 'booked' || b.status === 'called')
          && risky.some((r) => r.c.id === b.customerId));
        return {
          text: t('ans.noShow.list', { n: risky.length })
            + (todayRisky.length
              ? t('ans.noShow.onSheet', {
                n: todayRisky.length,
                who: todayRisky.map((b) => t('ans.noShow.at', {
                  name: custOf(state, b.customerId).name, time: hm12(b.time),
                })).join(', '),
              })
              : t('ans.noShow.noneToday')),
          table: {
            head: t('ans.noShow.cols'),
            rows: risky.map((r) => [r.c.name, String(r.st.noShows), `**${r.st.rate}%**`, String(r.st.upcoming)]),
          },
          suggestions: [t('ans.chips.queueNow'), t('ans.chips.todayLoad'), t('ans.chips.cancellations')],
        };
      },
    },
    {
      id: 'staff-load',
      match: [/utilisation|utilization|workload|how busy is|rota|working hours|who is on|who'?s on|shift|day off/i, 'staff'],
      trace: t('ans.trace.staff'),
      answer: (q, state) => {
        const staffId = matchStaff(state, q);
        const week = weekStart(todayKey());
        const days = Array.from({ length: 7 }, (_, i) => addDays(week, i));
        const pool = staffId ? state.staff.filter((s) => s.id === staffId) : state.staff;
        const rows = pool.map((st) => {
          const cap = days.reduce((n, d) => n + shiftMinutes(state, st.id, d), 0);
          const booked = live(state, days[0], days[6]).filter((b) => b.staffId === st.id);
          const mins = booked.reduce((n, b) => n + b.blockMin, 0);
          return [st.name, String(booked.length), `${mins} / ${cap}`, `**${cap ? Math.round((mins / cap) * 100) : 0}%**`];
        });
        const st = staffId ? staffOf(state, staffId) : null;
        return {
          text: st
            ? t('ans.staff.one', {
              name: st.name,
              role: staffRole(st),
              days: st.days.map((d) => dowLong(d).slice(0, 3)).join(', '),
              from: hm12(st.start),
              to: hm12(st.end),
              breakFrom: hm12(st.breakStart),
              breakTo: hm12(st.breakEnd),
              room: staffRoom(st),
              skills: st.skills.map((id) => svcName(svcOf(state, id))).join(', '),
            })
            : t('ans.staff.week', { day: dayLabel(week) }),
          table: { head: t('ans.staff.cols'), rows },
          suggestions: [t('ans.chips.nextAnwar'), t('ans.chips.todayLoad'), t('ans.chips.freeTomorrow')],
        };
      },
    },
    {
      id: 'service-mix',
      match: [/most booked|popular|top service|service mix|which service|best selling|earns most/i, 'services'],
      trace: t('ans.trace.services'),
      answer: (q, state) => {
        const from = addDays(todayKey(), -30);
        const rows = state.services.map((s) => {
          const list = state.bookings.filter((b) => b.serviceId === s.id && b.date >= from && b.date <= todayKey() && b.status === 'done');
          return { s, count: list.length, rev: list.length * s.priceInr };
        }).sort((a, b) => b.rev - a.rev);
        const top = rows[0];
        const total = rows.reduce((n, r) => n + r.rev, 0);
        return {
          text: t('ans.services.text', {
            money: money(state, total),
            done: rows.reduce((n, r) => n + r.count, 0),
            top: svcName(top.s),
            topMoney: money(state, top.rev),
            topCount: top.count,
          }),
          table: {
            head: t('ans.services.cols'),
            rows: rows.map((r) => [svcName(r.s), String(r.count), money(state, r.rev), t('common.minShort', { n: r.s.durationMin + r.s.bufferMin })]),
          },
          suggestions: [t('ans.chips.busiest'), t('ans.chips.takings'), t('ans.chips.freeTomorrow')],
        };
      },
    },
    {
      id: 'revenue',
      match: [/revenue|takings|billed|income|money|earned|how much/i, 'takings'],
      trace: t('ans.trace.revenue'),
      answer: (q, state) => {
        const tk = todayKey();
        const week = weekStart(tk);
        const sum = (from, to) => state.bookings
          .filter((b) => b.date >= from && b.date <= to && b.status === 'done')
          .reduce((n, b) => n + svcOf(state, b.serviceId).priceInr, 0);
        const booked = state.bookings
          .filter((b) => b.date >= tk && (b.status === 'booked' || b.status === 'called' || b.status === 'serving'))
          .reduce((n, b) => n + svcOf(state, b.serviceId).priceInr, 0);
        return {
          text: t('ans.revenue.text', {
            today: money(state, sum(tk, tk)),
            week: money(state, sum(week, tk)),
            month: money(state, sum(addDays(tk, -30), tk)),
            booked: money(state, booked),
            open: state.bookings.filter((b) => b.date >= tk && b.status === 'booked').length,
          }),
          meta: t('ans.revenue.meta'),
          suggestions: [t('ans.chips.earnsMost'), t('ans.chips.todayLoad'), t('ans.chips.cancellations')],
        };
      },
    },
    {
      id: 'cancellations',
      match: [/cancel|cancellation|dropped|released|freed up/i, 'cancellations'],
      trace: t('ans.trace.cancellations'),
      answer: (q, state) => {
        const tk = todayKey();
        const week = weekStart(tk);
        const end = addDays(week, 6);
        const thisWeek = state.bookings.filter((b) => b.date >= week && b.date <= end && b.status === 'cancelled');
        const prev = state.bookings.filter((b) => b.date >= addDays(week, -7) && b.date < week && b.status === 'cancelled');
        const byStaff = state.staff.map((st) => [st.name, String(thisWeek.filter((b) => b.staffId === st.id).length)]);
        return {
          text: t('ans.cancellations.text', {
            n: thisWeek.length,
            day: dayLabel(week),
            prev: prev.length,
            minutes: thisWeek.reduce((n, b) => n + b.blockMin, 0),
          }),
          table: { head: t('ans.cancellations.cols'), rows: byStaff },
          suggestions: [t('ans.chips.noShow'), t('ans.chips.freeTomorrow'), t('ans.chips.todayLoad')],
        };
      },
    },
    {
      id: 'customer-lookup',
      match: [/history for|tell me about|customer|record for|has .* been|when did .* last/i, 'history'],
      trace: t('ans.trace.customer'),
      answer: (q, state) => {
        const c = matchCustomer(state, q);
        if (!c) {
          return {
            text: t('ans.customer.noName', { n: state.customers.length }),
            suggestions: [t('ans.chips.noShow'), t('ans.chips.queueNow'), t('ans.chips.todayLoad')],
          };
        }
        const st = customerStats(state, c.id);
        const recent = state.bookings.filter((b) => b.customerId === c.id)
          .sort((a, b) => b.date.localeCompare(a.date)).slice(0, 5);
        return {
          text: t('ans.customer.text', {
            name: c.name,
            phone: c.phone,
            since: dayLabel(c.since),
            attended: st.attended,
            noShows: st.noShows,
            cancelled: st.cancelled,
            rate: st.rate,
            spend: money(state, st.spend),
            ahead: st.upcoming ? t('ans.customer.ahead', { n: st.upcoming }) : t('ans.customer.noneAhead'),
          }),
          table: {
            head: t('ans.customer.cols'),
            rows: recent.map((b) => [dayLabel(b.date), svcOf(state, b.serviceId).code, staffOf(state, b.staffId).name.split(' ')[0], (STATUS[b.status] || {}).label || b.status]),
          },
          suggestions: [t('ans.chips.noShow'), t('ans.chips.nextRehana')],
        };
      },
    },
    {
      id: 'desk-setup',
      match: [/opening hours|slot length|template|confirmation message|closed day|settings|how long is a slot/i, 'opening hours'],
      trace: t('ans.trace.setup'),
      answer: (q, state) => {
        const s = state.settings;
        return {
          text: t('ans.setup.text', {
            desk: deskName(state),
            branch: branchName(state),
            from: hm12(s.openTime),
            to: hm12(s.closeTime),
            slots: gridSlots(state).length,
            step: s.slotMinutes,
            closed: s.closedDays.length ? s.closedDays.map((d) => dowLong(d)).join(', ') : t('ans.setup.noFixedDay'),
            prefix: s.tokenPrefix,
            services: state.services.filter((x) => x.active).length,
            staff: state.staff.filter((x) => x.active).length,
            template: s.confirmTemplate.slice(0, 90),
          }),
          suggestions: [t('ans.chips.todayLoad'), t('ans.chips.freeTomorrow'), t('ans.chips.earnsMost')],
        };
      },
    },
  ];
}

export function buildAgent(ctx) {
  return new Assistant({
    name: t('agent.name'),
    initials: t('agent.initials'),
    tag: t('agent.tag'),
    greeting: t('agent.greeting'),
    suggestions: actionChips(),
    note: t('agent.note'),
    intents: [...intents(), ...actionIntents(ctx)],
    fallbacks: t('agent.fallbacks'),
    context: () => ctx.state,
    /* The panel's own furniture — lib/assistant.js keeps English defaults for
       apps that ship no dictionary, so it is handed this one's. */
    ui: {
      openAria: (name) => t('agent.ui.openAria', { name }),
      fabTitle: (name) => t('agent.ui.askAbout', { name }),
      clear: t('agent.ui.clear'),
      close: t('agent.ui.close'),
      placeholder: t('agent.ui.placeholder'),
      send: t('agent.ui.send'),
      you: t('agent.ui.you'),
      working: t('agent.ui.working'),
      done: t('agent.ui.done'),
      applied: t('agent.ui.applied'),
      edge: t('agent.ui.edgeCase'),
      failed: t('agent.ui.actionFailed'),
      searched: t('agent.ui.searched'),
    },
  });
}

export { matchDay, matchService, matchStaff, matchCustomer };
